const CONSULTS=[
{k:['比較利益','絕對利益'],e:'比較利益比較的是機會成本，不是誰做得比較快。先計算每生產一單位商品所放棄的另一商品數量；機會成本較低者具有比較利益。即使一方兩種商品都更有效率，專業化與交換仍可能讓雙方互利。',q:'小安做一杯飲料要放棄2個飯糰，小美做一杯飲料只放棄1個飯糰。誰在製作飲料上具有比較利益？',o:['小安，因為放棄得較多','小美，因為機會成本較低','兩人都沒有','必須先知道飲料售價'],a:1},
{k:['機會成本'],e:'機會成本不是全部支出，也不是已經付掉的沉沒成本，而是做出選擇後，放棄的最佳替代方案價值。解題時先列出替代方案，再找價值最高但被放棄的一個。',q:'週六下午你只能打工賺800元或參加免費球賽。你選擇看球，若不考慮其他成本，主要機會成本是什麼？',o:['零元，因為球賽免費','放棄的800元工資','以前買球鞋的錢','球場座位數'],a:1},
{k:['十大原理','誘因','邊際'],e:'經濟學十大原理的核心是稀少性下的選擇：人們面臨取捨、考慮機會成本、在邊際上決策並回應誘因；市場通常能協調活動，但政府有時可改善市場失靈。',q:'飲料店多開一小時，新增收入900元、新增人事與水電700元。用邊際分析應如何決定？',o:['不開，因總成本一定很高','開，因邊際利益大於邊際成本','只看昨天收入','必須等平均成本為零'],a:1},
{k:['需求'],e:'商品自身價格改變造成需求量沿既有曲線移動；所得、偏好、預期、相關商品價格或買者人數改變，才會使整條需求曲線位移。先辨認改變的是自身價格還是其他因素。',q:'咖啡價格不變，但珍珠奶茶價格上漲後，更多人改買咖啡。咖啡市場最可能怎麼變？',o:['咖啡需求增加','咖啡需求量因自身價格下降','咖啡供給減少','咖啡需求不變'],a:0},
{k:['供給'],e:'商品自身價格改變造成供給量沿曲線移動；投入成本、技術、預期、賣者數量或相關產品報酬改變，會使供給曲線位移。成本下降或技術進步通常使供給增加。',q:'麵粉價格上漲，而麵包售價暫時不變。麵包市場最可能出現什麼變化？',o:['需求增加','供給減少','供給量增加','需求量減少'],a:1},
{k:['均衡','短缺','剩餘','供需'],e:'市場均衡在需求量等於供給量之處。價格低於均衡時會短缺並形成上漲壓力；價格高於均衡時會剩餘並形成下跌壓力。曲線位移後要同時追蹤均衡價格與數量。',q:'演唱會票價被設定在均衡價格以下，最可能出現什麼？',o:['供給過剩','需求短缺','超額需求與排隊','市場立即出清'],a:2},
{k:['彈性'],e:'需求價格彈性衡量需求量對價格變動的敏感程度。絕對值大於1為富有彈性，小於1為缺乏彈性。缺乏彈性時，漲價通常使總收益增加；富有彈性時則相反。',q:'通勤族對捷運需求缺乏彈性。若票價小幅上漲且其他條件不變，捷運總收益通常如何？',o:['增加','減少','一定為零','無法用彈性判斷'],a:0},
{k:['價格管制','價格上限','價格下限'],e:'有效的價格上限必須低於均衡價格，常造成短缺；有效的價格下限必須高於均衡價格，常造成剩餘。分析時也要考慮排隊、黑市、品質下降或政府收購等非價格效果。',q:'政府把租金上限設在市場均衡租金以下，最可能出現什麼？',o:['空屋大量增加','租屋需求小於供給','租屋短缺與排隊','均衡價格自動下降且沒有副作用'],a:2},
{k:['邊際效用','總效用'],e:'邊際效用是多消費一單位帶來的總效用增加量，通常遞減。有限預算下，消費者會比較每一元支出帶來的邊際效用，調整到各商品每元邊際效用大致相等。',q:'你最後一杯飲料每元帶來的效用高於最後一份點心。若能調整消費，應怎麼做？',o:['多買點心、少買飲料','多買飲料、少買點心','兩者都不買','只比較商品總價'],a:1},
{k:['無異曲線','預算線','邊際替代率'],e:'無異曲線上的組合帶來相同滿足程度，通常向右下傾斜且凸向原點；預算線顯示所得與價格限制。內部最適點常在無異曲線與預算線相切，亦即邊際替代率等於相對價格。',q:'所得增加且兩商品價格不變時，預算線通常如何變化？',o:['平行向外移','平行向內移','只改變斜率','完全不變'],a:0},
{k:['生產函數','邊際產量','平均產量'],e:'生產函數描述投入與最大產出的技術關係。短期至少有一項固定投入；增加變動投入後，邊際產量最終常因固定資源擁擠而遞減。',q:'小廚房大小不變，持續增加廚師後，每多一位廚師增加的餐點數逐漸變少。這是什麼現象？',o:['需求法則','邊際產量遞減','規模經濟','比較利益'],a:1},
{k:['生產成本','固定成本','變動成本','邊際成本'],e:'總成本等於固定成本加變動成本；平均成本是每單位成本；邊際成本是多生產一單位的額外成本。當邊際成本低於平均成本時會拉低平均成本，反之則推高。',q:'某店平均成本為80元，而下一份餐點的邊際成本為60元。生產這一份後，平均成本通常如何？',o:['上升','下降','一定不變','變成零'],a:1},
{k:['規模經濟','規模不經濟','規模報酬'],e:'規模經濟是長期擴大產量後平均成本下降，可能來自專業化、設備分攤或採購優勢；組織溝通與管理負擔過大則可能形成規模不經濟。',q:'連鎖烘焙店擴大產量後，可分攤中央廚房設備成本，使每個麵包平均成本下降。這屬於什麼？',o:['規模經濟','需求增加','邊際效用遞減','價格上限'],a:0},
{k:['總收益','邊際收益','平均收益'],e:'總收益TR等於價格乘數量；平均收益通常等於每單位價格；邊際收益MR是多賣一單位所增加的總收益。面對向下需求曲線的廠商，為多賣一單位常須降價，因此MR通常小於價格。',q:'獨占電影院降價才能多賣一張票。新增一張票的邊際收益通常與新票價相比如何？',o:['較大','相等','較小','必定為負'],a:2},
{k:['市場結構'],e:'市場結構可從廠商數量、產品差異、進入障礙與價格控制力判斷。完全競爭產品同質且廠商多；獨占只有單一供給者且障礙高；寡占重視策略互動；獨占性競爭則有許多差異化產品。',q:'一條街有許多咖啡店，各自用品牌與風味區隔，而且新店可進入。最接近哪種市場？',o:['完全競爭','獨占','寡占','獨占性競爭'],a:3},
{k:['完全競爭','價格接受者'],e:'完全競爭廠商是價格接受者，因此P等於MR。短期在MR等於上升段MC處決定產量；若價格低於平均變動成本，停業可減少損失。長期因自由進出，經濟利潤會趨近零。',q:'完全競爭早餐店短期面對的價格低於平均變動成本，較合理的決策是什麼？',o:['持續生產任何數量','暫時停業','立刻提高市場價格','忽略變動成本'],a:1},
{k:['獨占'],e:'獨占者面對市場向下傾斜需求，通常MR小於P。它先以MR等於MC決定利潤最大產量，再由需求曲線找價格；結果常較競爭市場價高量少並產生無謂損失。',q:'獨占廠商已用MR＝MC決定產量後，應到哪裡決定售價？',o:['需求曲線','邊際成本曲線','平均固定成本曲線','供給曲線'],a:0},
{k:['寡占','卡特爾','賽局','納許'],e:'寡占市場只有少數主要廠商，彼此決策互相影響，因此常用賽局分析。合作可提高共同利潤，但每家廠商可能有偷跑誘因；納許均衡表示給定他人策略時，沒有人願意單方面改變。',q:'兩家飲料大廠約定不降價，但每家都能靠偷偷促銷搶客。這最能說明什麼？',o:['合作一定穩定','卡特爾可能因個別誘因而瓦解','市場沒有策略互動','產品一定同質'],a:1},
{k:['獨占性競爭','壟斷性競爭'],e:'獨占性競爭有許多廠商、產品差異與相對自由進出。短期可能有利潤，長期新廠商進入使個別需求減少，經濟利潤趨近零，但通常仍有超額產能。',q:'特色甜點店短期獲得高利潤，且其他店很容易模仿進入。長期最可能如何？',o:['新店進入，原店需求與利潤下降','原店永久維持高利潤','市場變成單一賣方','邊際成本必定為零'],a:0},
{k:['資訊不對稱','逆向選擇','道德危險'],e:'資訊不對稱是交易雙方掌握資訊不同。逆向選擇發生在交易前的隱藏資訊，例如買方難辨二手車品質；道德危險發生在交易後的隱藏行動，例如投保後降低防範。保固、認證、聲譽與自負額可協助緩解。',q:'駕駛投保全險後，因損失有人分擔而更少保養車輛。這屬於什麼？',o:['比較利益','逆向選擇','道德危險','規模經濟'],a:2}
];
function consultTopic(text){let t=text.toLowerCase();return CONSULTS.find(x=>x.k.some(k=>t.includes(k.toLowerCase())))}
function consultHistory(){return JSON.parse(localStorage.getItem('econConsultHist')||'[]')}
function saveConsult(entry){let h=consultHistory();h.unshift(entry);localStorage.setItem('econConsultHist',JSON.stringify(h));if(typeof syncRecord==='function')syncRecord('consult',{className:entry.className,studentId:entry.id,topic:entry.topic,question:entry.question,answer:entry.answer,consultId:entry.consultId})}
function tutor(){return `<p class="kicker">AI 諮詢專線</p><h1 class="title">先解惑，再確認真的理解</h1><div class="chips">${['比較利益怎麼判斷？','什麼是機會成本？','需求與需求量有何不同？','獨占為何有無謂損失？'].map(x=>`<button class="chip" data-p="${x}">${x}</button>`).join('')}</div><section class="card chat"><div class="msgs" id="msgs"><div class="msg"><b>AI 小博士</b>請一次問一個經濟問題。我會先用觀念與判斷步驟解惑，接著立刻出一題生活情境四選一，確認你是否理解。</div></div><form class="ask" id="ask"><textarea id="question" placeholder="例如：比較利益和絕對利益差在哪裡？" required></textarea><button class="btn primary">送出</button></form></section><div class="note">目前優先使用課程教材整理的20單元知識；外部檢索功能將由伺服器端串接，以保護模型金鑰並保留資料來源。</div>`}
function send(text){let topic=consultTopic(text),explain=topic?topic.e:'我目前無法從這句話判定明確單元。請補上完整題目、選項或關鍵概念，例如供需、彈性、效用、生產成本、市場結構、比較利益等，我會依「觀念、判斷步驟、結論」協助你。';msgs.insertAdjacentHTML('beforeend',`<div class="msg user">${esc(text)}</div><div class="msg"><b>AI 小博士 · 解惑</b>${esc(explain)}</div>`);if(topic){let consultId=String(Date.now())+"-"+String(Math.random());S.check={topic,text,consultId};msgs.insertAdjacentHTML('beforeend',`<div class="msg check"><b>理解檢核 · 生活情境題</b>${esc(topic.q)}<div class="opts" style="margin-top:10px">${topic.o.map((o,i)=>`<button class="opt" onclick="checkConsult(${i},this)">${String.fromCharCode(65+i)}. ${esc(o)}</button>`).join('')}</div></div>`)}saveConsult({time:Date.now(),date:new Date().toLocaleString('zh-TW'),id:S.student.id,className:S.student.className,question:text,topic:topic?topic.k[0]:'未分類',answer:explain,check:null,consultId:S.check?.consultId||String(Date.now())+"-"+String(Math.random())});msgs.scrollTop=msgs.scrollHeight}
function checkConsult(choice,button){if(!S.check)return;let topic=S.check.topic,correct=choice===topic.a;button.parentElement.querySelectorAll('button').forEach((b,i)=>{b.disabled=true;if(i===topic.a)b.style.borderColor='#0b8f83';if(i===topic.a)b.style.background='#dff8f4';if(i===choice&&!correct)b.style.background='#fee2e2'});let message=correct?'答對了！你已掌握這個概念。還想了解什麼？可以直接在下方繼續問我。':`還差一點。正確答案是 ${String.fromCharCode(65+topic.a)}，因為：${topic.e} 你可以再問我其中不清楚的步驟。`;msgs.insertAdjacentHTML('beforeend',`<div class="msg"><b>AI 小博士</b>${esc(message)}</div>`);let h=consultHistory();let item=h.find(x=>x.id===S.student.id&&x.question===S.check.text);if(item){item.check={question:topic.q,choices:topic.o,studentChoice:choice,correctChoice:topic.a,isCorrect:correct};localStorage.setItem('econConsultHist',JSON.stringify(h))}S.check=null;msgs.scrollTop=msgs.scrollHeight}