Object.keys(raw).forEach(k=>delete raw[k]);Object.assign(raw,window.QUESTION_BANK||{});
function isChoice(q){return Array.isArray(q[1])}
function right(q,a){return isChoice(q)?a===q[2]:a===q[1]}
function ansText(q,a){if(a===null||a===undefined)return '未作答';return isChoice(q)?`${String.fromCharCode(65+a)}. ${q[1][a]}`:(a?A:B)}
function detail(q){return isChoice(q)?q[3]:q[2]}
function units(){return `<p class="kicker">隨時測驗</p><h1 class="title">選擇練習單元</h1><p>題庫達10題時隨機抽10題；少於10題時抽5題。每次均換算為100分。</p><div class="units">${Object.keys(raw).map((u,i)=>`<button class="unit" data-unit="${esc(u)}"><small>UNIT ${i+1} · 題庫 ${raw[u].length} 題 · 本次 ${raw[u].length<10?5:10} 題</small><b>${esc(u)}</b></button>`).join('')}</div>`}
function quiz(){let q=S.quiz.qs[S.i],opts=isChoice(q)?q[1]:['錯誤','正確'];return `<p class="kicker">${esc(S.quiz.unit)}</p><h1 class="title">第 ${S.i+1} 題／${S.quiz.qs.length}</h1><div class="progress"><span style="width:${(S.i+1)*100/S.quiz.qs.length}%"></span></div><section class="card question"><h2>${esc(q[0])}</h2><div class="opts">${opts.map((o,i)=>`<button class="opt ${S.ans[S.i]===i?'sel':''}" data-a="${i}">${String.fromCharCode(65+i)}. ${esc(o)}</button>`).join('')}</div></section><div class="actions"><button class="btn ghost" id="prev">${S.i?'← 上一題':'返回單元'}</button><button class="btn primary" id="next" ${S.ans[S.i]===null?'disabled':''}>${S.i===S.quiz.qs.length-1?'交卷看結果':'下一題 →'}</button></div>`}
function finish(){let n=S.quiz.qs.reduce((v,q,i)=>v+Number(right(q,S.ans[i])),0),r={time:Date.now(),date:new Date().toLocaleString('zh-TW'),id:S.student.id,className:S.student.className,unit:S.quiz.unit,score:Math.round(n*100/S.quiz.qs.length),n,total:S.quiz.qs.length,qs:S.quiz.qs,ans:S.ans};let h=hist();h.unshift(r);save(h);if(typeof syncRecord==='function')syncRecord('quiz',{className:r.className,studentId:r.id,unit:r.unit,total:r.total,score:r.score,correctCount:r.n,quizId:String(r.time),answers:r.qs.map((q,i)=>({number:i+1,question:q[0],studentAnswer:ansText(q,r.ans[i]),correctAnswer:ansText(q,isChoice(q)?q[2]:q[1]),isCorrect:right(q,r.ans[i]),explanation:detail(q)}))});app.innerHTML=shell(result(r));nav();retry.onclick=()=>start(r.unit);other.onclick=()=>render('units')}
function result(r){let msg=r.score===100?'👍 太棒了，滿分！AI小博士為你按讚，你已完整掌握這個單元。':r.score<60?'AI小博士陪你再練一次！錯題正在告訴我們下一步要加強哪裡。':'AI小博士：做得很好，看完詳解再挑戰一次會更穩。';return `<section class="result"><div><p class="kicker" style="color:#8ff1e7">測驗完成</p><h1>${esc(r.unit)}</h1><p>答對 ${r.n}／${r.total} 題</p><p>${msg}</p></div><div class="score">${r.score}</div></section><div class="actions"><button class="btn ghost" id="other">選其他單元</button><button class="btn primary" id="retry">再練一次</button></div>${r.qs.map((q,i)=>review(q,r.ans[i],i)).join('')}`}
function review(q,a,i){return `<article class="card review ${right(q,a)?'':'bad'}"><b>第 ${i+1} 題 · ${right(q,a)?'答對':'答錯'}</b><p>${esc(q[0])}</p><p>學生答案：${esc(ansText(q,a))}</p><p>正確答案：${esc(ansText(q,isChoice(q)?q[2]:q[1]))}</p><p>詳解：${esc(detail(q))}</p></article>`}
function consultationRecords(){return consultHistory().filter(x=>x.id===S.student.id&&x.className===S.student.className)}
function history(){let tests=mine(),asks=consultationRecords(),allCount=tests.length+asks.length;return `<p class="kicker">個人學習歷程</p><h1 class="title">完整學習歷程</h1><div class="stats"><div class="stat"><b>${tests.length}</b><small>測驗次數</small></div><div class="stat"><b>${asks.length}</b><small>諮詢次數</small></div><div class="stat"><b>${allCount}</b><small>學習活動</small></div></div><h2>測驗答題紀錄</h2>${tests.length?`<div class="history">${tests.map(r=>`<details class="card review"><summary><b>${esc(r.unit)}</b>　<strong>${r.score}分</strong><br><small>${esc(r.date)} · 答對 ${r.n}/${r.total||r.qs.length}</small></summary><div>${r.qs.map((q,i)=>review(q,r.ans[i],i)).join('')}</div></details>`).join('')}</div>`:'<div class="card empty">尚無測驗紀錄</div>'}<h2 style="margin-top:28px">AI諮詢紀錄</h2>${asks.length?`<div class="history">${asks.map(x=>`<details class="card review"><summary><b>${esc(x.topic)}</b><br><small>${esc(x.date)}</small></summary><p><b>學生提問</b><br>${esc(x.question)}</p><p><b>AI解惑</b><br>${esc(x.answer)}</p>${x.check?`<p><b>生活情境檢核題</b><br>${esc(x.check.question)}</p><p>學生答案：${esc(`${String.fromCharCode(65+x.check.studentChoice)}. ${x.check.choices[x.check.studentChoice]}`)}</p><p>正確答案：${esc(`${String.fromCharCode(65+x.check.correctChoice)}. ${x.check.choices[x.check.correctChoice]}`)}</p><p><b>${x.check.isCorrect?'答對':'答錯'}</b></p>`:'<p>尚未完成理解檢核題</p>'}</details>`).join('')}</div>`:'<div class="card empty">尚無AI諮詢紀錄</div>'}`}